### ISSUE TITLE
Movimento - limitar area de movimento 

### ISSUE THREAD

**Issue by rfabbri** [rfabbri/pet#12]
Limitar a area de movimento do coelho somente pelo chao do quarto.

http://wiki.nosdigitais.teia.org.br/Pet#Falta

@leosimoes @geovanecomp

**Comment by leosimoes** [comment]
Não achei no playN pythagoras com polygon e incidentTest.
Achei a apenas a classe Polygon do Java que cria um poligono com um array de x, array de y e seu comprimento, e o método contains que verifica se um ponto está contido no poligono.

**Comment by rfabbri** [comment]
oi, fechei a tarefa usando Area do Pythagoras. obrigado pela info desse
outro poligono q pode vir a ser util. prox passo sera implementar menores
caminhos e planejamento de trajetorias p coelho evitar obstaculos

abs

On Friday, January 2, 2015, leosimoes <notifications@github.com> wrote:

> Não achei no playN pythagoras com polygon e incidentTest.
> Achei a apenas a classe Polygon do Java que cria um poligono com um array
> de x, array de y e seu comprimento, e o método contains que verifica se um
> ponto está contido no poligono.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rfabbri/pet/issues/12#issuecomment-68529208>.
>


-- 

--
Dr Ricardo Fabbri
Professor of Computer Engineering
GNU/Linux registered user #175401
www.lems.brown.edu/~rfabbri
pt.wikipedia.org/wiki/IPRJ
labmacambira.sf.net
