### ISSUE TITLE
Lendo livro Head First Java, Second Edition

### ISSUE THREAD

**Issue by pliniopereira** [rfabbri/pet#44]

**Comment by prestoppc** [comment]
Como esta a leitura? Aprendendo algumas coisas massas?

**Comment by pliniopereira** [comment]
Aprendendo muito pouco ainda, estou mais adaptando a linguagem mesmo.

**Comment by pliniopereira** [comment]
Vídeo-aulas interessantes:
https://www.youtube.com/user/italogross/playlists
https://www.youtube.com/watch?v=NZDzuve7kho&index=1&list=PLxQNfKs8YwvGhXHbHtxtoB-tRRv6r3Rlr
https://www.youtube.com/user/excriptvideo/playlists

**Comment by rfabbri** [comment]
Plinio,
Para voce conseguir aprender precisa ter um objetivo pratico em mente ao
mesmo tempo.

O presto esta aprendendo lua, por exemplo, mas tem um App em mente e sempre
vai fazendo seus proprios programas. Voce deveria tentar fazer algumas
modificacoes, mesmo que simples, no Pet enquanto ao mesmo tempo vai
seguindo tutoriais e livros.

abs


--
Dr Ricardo Fabbri
Professor of Computer Engineering
GNU/Linux registered user #175401
www.lems.brown.edu/~rfabbri
pt.wikipedia.org/wiki/IPRJ
labmacambira.sf.net

**Comment by pliniopereira** [comment]
Faz todo sentido!
