### ISSUE TITLE
Ligar som dos dejetos

### ISSUE THREAD

**Issue by rfabbri** [rfabbri/pet#66]
A cada tipo de dejeto dropado ha um som associado. Basicamente olhar o codigo em PetOld.java que tem como tocar um arquivo mp3 e colocar na logica da nova engine.
ver http://wiki.nosdigitais.teia.org.br/Pet#Falta

**Comment by prestoppc** [comment]
Agreguei o mapa do som ao nosso arquivo de controle do andamento do projeto:

https://docs.google.com/spreadsheets/d/1e4jvthYTdHw48ogcJQY2X9z3QN47hcOYC_-5bwNH01Y/edit?usp=sharing

**Comment by geovanecomp** [comment]
@rfabbri  @prestoppc 
Pessoal, posso tentar fazer essa tarefa?

**Comment by geovanecomp** [comment]
Bem, acabei fazendo essa tarefa, espero que não tenha problema.
Agora quando o pingo faz coco, ele emite um som. Como não tenho o áudio dele fazendo coco, estou usando temporariamente o áudio dele arrotando.

**Comment by prestoppc** [comment]
Perfeito Geovane. Manda bala!!

**Comment by prestoppc** [comment]
Geovanne, VC deu commit e push? Se terminou já pode dar commit

**Comment by geovanecomp** [comment]
Já dei o push sim, só não fechei a tarefa ainda, pq preciso do som correto.

Quando puder, vc me envia o som?

2015-01-12 22:15 GMT-02:00 prestoppc <notifications@github.com>:

**Comment by prestoppc** [comment]
Vou completar o mapa de som. Vou abrir ticket. Valeu Geovane
Em 14/01/2015 16:18, "Geovane" <notifications@github.com> escreveu:

**Comment by rfabbri** [comment]
Geovane,
sinto muito te dizer assim mas..
*voce marcou muita bobeira*
eita..
equeceu que o MASTER ja esta anos luz `a frente do seu branch geovane3??

no master ja tem uma sound engine completa

viajou e repetiu trabalho....

da um gitk --all de vez em quando!


--
Dr Ricardo Fabbri
Professor of Computer Engineering
GNU/Linux registered user #175401
www.lems.brown.edu/~rfabbri
pt.wikipedia.org/wiki/IPRJ
labmacambira.sf.net

2015-01-14 18:32 GMT-02:00 prestoppc <notifications@github.com>:

**Comment by rfabbri** [comment]
PS: vc tem o devido credito pois pelo menos tentou tomar iniciativa.. mas
tem que aprender git! o certo teria sido dar primeiro um rebase do seu
branch no master *antes* de escrever o novo codigo, conforme voce ja leu e
deve lembrar no livro git pro (eu mesmo releio sempre essas partes pra
tentar lembrar e nao fazer bobeira).


--
Dr Ricardo Fabbri
Professor of Computer Engineering
GNU/Linux registered user #175401
www.lems.brown.edu/~rfabbri
pt.wikipedia.org/wiki/IPRJ
labmacambira.sf.net

2015-01-16 16:35 GMT-02:00 Ricardo Fabbri <rfabbri@gmail.com>:

**Comment by geovanecomp** [comment]
Sim @rfabbri, não dei o git -all não, pq olhei todas as tarefas alocadas no git e vi esta, que não tinha ninguém trabalhando nela ou em algo relacionado a ela (aparentemente). Além disso, na descrição da tarefa está escrito: 
"... Basicamente olhar o codigo em PetOld.java que tem como tocar um arquivo mp3 e colocar na logica da nova engine."

Então eu segui as instruções da tarefa e fiz.

Eu rushei nessa tarefa pra ter + uma tarefa feita, já que estou bem enrolado com provas e trabalhos de final de período. Na próxima vez não me guiarei apenas pelas tarefas do git e suas respectivas descrições.

**Comment by geovanecomp** [comment]
Tarefa feita utilizando a nova engine, como não sei se o fabbri vai querer ver algo do branch antigo, criei o branch geovane4 por precaução.

Sobre o som do pingo fazendo coco, não o encontrei no branch master, entao inseri um arquivo pum.mp3 pra tocar quando pingo faz coco.
@rfabbri quando puder da uma olhada se está OK, se sim eu fecho a tarefa. Abs.

**Comment by rfabbri** [comment]
vou conferir em breve. estava ocupado com a script engine de Lua abs.
