### ISSUE TITLE
adicionar

### ISSUE THREAD

**Issue by rfabbri** [rfabbri/pet#78]
Olá amigxs, podem adicionar mais este elemente subersivo a lista? Abrxs!
tcavalcanti@id.uff.br
-- 
*Frederico Ronconi*
(41) 8824-0060
Psicólogo - CRP-PR 08/16224
Psicologia Clínica - Saúde Mental

-- 
Você está recebendo esta mensagem porque se inscreveu no grupo "listamacambira" dos Grupos do Google.
Para cancelar inscrição nesse grupo e parar de receber e-mails dele, envie um e-mail para listamacambira+unsubscribe@googlegroups.com.
Para obter mais opções, acesse https://groups.google.com/d/optout.

**Comment by prestoppc** [comment]
esse item nao se aplica ao pet. Fechando o ticket
