### ISSUE TITLE
Glicose limitada

### ISSUE THREAD

**Issue by prestoppc** [rfabbri/pet#94]
Glicose. Caso o Pingo fique MUITO BÊBADO (*fazer animação do Pingo MUITO
BEBADO) e venha a entrar em COMA ALCOOLICO (* fazer animação do Pingo em COMA ALCOOLICO), o jogador deve dar GLICOSE ao Pingo para sair do coma. Apos usar a glicose, ela fica travada até o dia seguinte. A bebida ficava liberada sob responsabilidade do jogador.

**Comment by rfabbri** [comment]
ja havia sido feito em outro ticket.
